title: Stackbit DIY Theme
baseURL: /
params:
  layout_type: full-width
  style: bold
  palette: green
  mode: light
  base_font: sans-serif
  header:
    type: header
    template: header
    title: DIY
    logo: /images/perpetual-mahogany.png
    logo_alt: DIY logo
    has_primary_nav: true
    primary_nav_links:
      - type: action
        template: action
        label: Course
        url: /course
        style: link
    has_secondary_nav: true
    secondary_nav_links:
      - type: action
        template: action
        label: Contact
        url: 'mailto:Pinhoti100@gmail.com'
        style: link
      - type: action
        template: action
        label: REgister
        url: 'https://ultrasignup.com/register.aspx?did=31286'
        style: primary
    has_anncmnt: true
    anncmnt_content: >-
      Register now for 2021's Race. **[Register on
      UltraSignup](https://ultrasignup.com/register.aspx?did=81711)**
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: new-features
  footer:
    type: footer
    template: footer
    logo: /images/perpetual-mahogany.png
    logo_alt: DIY logo
    has_primary_nav: true
    primary_nav_title: Company
    primary_nav_links:
      - type: action
        template: action
        label: About
        url: /about
        style: link
      - type: action
        template: action
        label: Style Guide
        url: /style-guide
        style: link
    has_secondary_nav: true
    secondary_nav_title: Blog
    secondary_nav_links:
      - type: action
        template: action
        label: News
        url: /blog/category/news
        style: link
      - type: action
        template: action
        label: General
        url: /blog/category/general
        style: link
      - type: action
        template: action
        label: Tutorials
        url: /blog/category/tutorials
        style: link
    has_tertiary_nav: true
    tertiary_nav_title: Legal
    tertiary_nav_links:
      - type: action
        template: action
        label: Terms & Conditions
        url: /terms-conditions
        style: link
      - type: action
        template: action
        label: Privacy Policy
        url: /privacy-policy
        style: link
    has_social: true
    social_links:
      - type: action
        template: action
        label: Twitter
        url: 'https://twitter.com/'
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - type: action
        template: action
        label: GitHub
        url: 'https://github.com/'
        style: link
        has_icon: true
        icon: github
        icon_position: center
        new_window: true
      - type: action
        template: action
        label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
      - type: action
        template: action
        label: YouTube
        url: 'https://www.youtube.com/'
        style: link
        has_icon: true
        icon: youtube
        icon_position: center
        new_window: true
      - type: action
        template: action
        label: Vimeo
        url: 'https://vimeo.com/'
        style: link
        has_icon: true
        icon: vimeo
        icon_position: center
        new_window: true
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=diy&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
  domain: 'https://clever-ant-b3a5f.netlify.app'
  favicon: /images/logo.png
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
